### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by rushiranpise** [eliasbenb/MagnetMagnet#3]
Can you add support to run this app on Heroku?

**Comment by eliasbenb** [comment]
Is this a troll? You do realize if I were to do that I would have to rewrite the entire framework the app is built on. So no.

**Comment by rushiranpise** [comment]
> Is this a troll? You do realize if I were to do that I would have to rewrite the entire framework the app is built on. So no.

Okay no problem 😊, btw this app is really good 👍 So i thought a heroku or any other service development would be a easy option to access if someone doesn't have pc time-to-time. Anyway, i really appreciate your work 👍
