### ISSUE TITLE
Not really an issue:   Just another approach to parsing the scrape of rarbg

### ISSUE THREAD

**Issue by dkluis** [eliasbenb/MagnetMagnet#7]
Thank you for all the info I found in your MagnetMagnet python set up.

I have played around a little with the rarbg and found a different way to parse the json coming back.

Just have pasted the code below to see if you can use it in the future:

`
import requests
import os

main_link = 'https://torrentapi.org/pubapi_v2.php?mode=search&search_string=almost paradise s01e08&token=lnjzy73ucv&format=json_extended&app_id=lol'

main_request = requests.get(main_link, headers={'User-Agent': 'Mozilla/5.0'}).json()
if main_request == {'error': 'No results found', 'error_code': 20}:
    quit("Not Found")

titles = main_request['torrent_results']
dl_options = []
for title in titles:
    name = title['title']
    magnet = title['download']
    seeders = title['seeders']
    size = title['size']
    dl_options.append((size, seeders, name, magnet))

dl_options.sort(reverse=True)

print()
for dl in dl_options:
    print(dl[0], dl[1], dl[2], dl[3])
    print()

print(dl[0][0])
quit()

print('Starting Download via RARBG', dl_options[0][3])
command_str = 'open -a transmission ' + dl_options[0][4]
os.system(command_str)
`

**Comment by eliasbenb** [comment]
Wow. This is way more efficient! MagnetMagnet was my first project, so I didn't learn JSON yet (still haven't) and went for web scraping with beautiful soup and requests first.

I'll read into your code and try to understand it within the next 2 days.
Thank you for your interest in my project 😃

**Comment by eliasbenb** [comment]
I've tried to use you're code, but it added complications with how I set up my code.
So I've just spared myself the headache and didn't bother swapping out the code.

Hey, if it ain't broke don't fix it.
Sorry for not using your great code.
