### ISSUE TITLE
[Feature Request] Search option features for ease of use

### ISSUE THREAD

**Issue by Tidsuo** [eliasbenb/MagnetMagnet#9]
First off this application is great for gathering magnet links! I'm so glad I found it.

Using it for a while I thought of some features for the search option

- Have the ability set custom range for more results than 20 if needed, helpful for media with many episodes.
- Each listed result have a toggle box to allow all marked results to either be copied to the clipboard or saved to a file like the standard operation instead of copying all desired results individually.
- A pop-up box for the selected results' magnet links to copy instead of creating a file with all the links.

**Comment by eliasbenb** [comment]
I don't maintain this project anymore, but these are some really good suggestions.

The first 2 suggestions would we easy to implement, the last not so much.

I might return to maintaining this project, but it definitely won't be any time soon.

Thank you for your interest in my project.
